name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: makefile
      run: make
    - name: batch_test
      run: ./RPS_batch_mar_vs_sec

