# This workflow performs a make check

name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: makefile
      working-directory: ./src/
      run: make
  
  unit_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: batch_test
      working-directory: ./bin/
      run: ./RPS_batch_mar_vs_sec
